In [1]:
import torch
torch.__version__

'2.7.1+cu128'

In [2]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [3]:
TENSOR.ndim

3

In [4]:
TENSOR.shape

torch.Size([1, 3, 3])

In [5]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
TENSORTEST = torch.tensor([[[1,2,3,6,8],
                            [5,3,6,8,8],
                            [3434, 355, 55,8,8]]])
TENSORTEST


tensor([[[   1,    2,    3,    6,    8],
         [   5,    3,    6,    8,    8],
         [3434,  355,   55,    8,    8]]])

In [7]:
### RAndom tensors

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3492, 0.3877, 0.9437, 0.0194],
        [0.3047, 0.0732, 0.1936, 0.3873],
        [0.9110, 0.3593, 0.0874, 0.4073]])

In [8]:
random_tensor.ndim

2

In [9]:
# tensor similiar shape to an image

random_image_size_tensor = torch.rand(size=(224,224,3)) # height width colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [10]:
torch.rand(3,3)

tensor([[0.4518, 0.1268, 0.9906],
        [0.2462, 0.6999, 0.5178],
        [0.8199, 0.8382, 0.1545]])

In [11]:
# Create a tensor of all zeros 

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
ones.dtype

torch.float32

In [15]:
random_tensor.dtype

torch.float32

In [28]:
# RAnge

one_to_ten = torch.arange(1, 10)

one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None, # datatype
                               device= None, # "CPU" or "CUDA"
                               requires_grad=False) # track gradient
float_32_tensor

tensor([3., 6., 9.])

In [48]:
float_32_tensor.dtype

torch.float32

In [50]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [59]:
float_multi = float_16_tensor * float_32_tensor 
float_multi, float_multi.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [ ]:
int_32_tensor = torch.tensor( [3, 6 ,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9])

In [65]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])