In [3]:
import torch
torch.__version__

'2.7.1+cu128'

In [5]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [6]:
TENSOR.ndim

3

In [7]:
TENSOR.shape

torch.Size([1, 3, 3])

In [8]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
TENSORTEST = torch.tensor([[[1,2,3,6,8],
                            [5,3,6,8,8],
                            [3434, 355, 55,8,8]]])
TENSORTEST


tensor([[[   1,    2,    3,    6,    8],
         [   5,    3,    6,    8,    8],
         [3434,  355,   55,    8,    8]]])

In [69]:
### RAndom tensors

random_tensor = torch.rand(3, 4)
random_tensor
del random_tensor

In [56]:
random_tensor. ndim

2

In [57]:
# tensor similiar shape to an image

random_image_size_tensor = torch.rand(size=(224,224,3)) # height width colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [58]:
torch.rand(3,3)

tensor([[0.8425, 0.5580, 0.4507],
        [0.6850, 0.9246, 0.2878],
        [0.6330, 0.1963, 0.5831]])

In [61]:
# Create a tensor of all zeros 

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [62]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [66]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [67]:
ones.dtype

torch.float32

In [68]:
random_tensor.dtype

torch.float32