# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
x = torch.randn(7, 7)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [14]:
# Create another random tensor
y = torch.randn(1,7)

# Perform matrix multiplication 
 
z = x * y
z, z.shape

(tensor([[ 1.0787,  1.0329, -0.2797, -0.0269,  0.4555, -0.8814, -0.4109],
         [-1.1908,  1.1389,  0.2824,  0.0638, -0.8806,  0.1832,  0.8966],
         [-0.2291,  0.3259, -1.1922,  0.2376,  1.0053,  0.5384, -0.4500],
         [ 0.6995,  0.4271, -1.0247, -0.0848, -0.5354, -0.3724,  0.5037],
         [-1.4401, -0.7607,  0.3381, -0.0918, -1.3418, -0.2131,  1.1457],
         [-0.3245, -0.3260, -0.8163,  0.2750, -0.5767, -0.1614,  0.6380],
         [-0.0296, -1.9570,  1.8268,  0.1092,  0.1376,  0.2253, -1.4481]]),
 torch.Size([7, 7]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [24]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
rand1 = torch.randn(7, 1)
torch.manual_seed(RANDOM_SEED)
rand2 = torch.randn(7, 1)

# Matrix multiply tensors
rand3 = rand1 * rand2
rand3, rand3.shape

(tensor([[2.3747],
         [0.0861],
         [4.7471],
         [0.3231],
         [1.1762],
         [1.9561],
         [0.1627]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [26]:
# Set random seed on the GPU
torch.cuda.manual_seed_all(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [42]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU

randn1 = torch.randn(2, 3).to(device)
randn2 = torch.randn(2, 3).to(device)

randn1, randn2


Device: cpu


(tensor([[ 0.0461,  0.4024, -1.0115],
         [ 0.2167, -0.6123,  0.5036]]),
 tensor([[ 0.2310,  0.6931, -0.2669],
         [ 2.1785,  0.1021, -0.2590]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
randn2 = torch.

In [53]:
# Perform matmul on tensor_A and tensor_B
randn3 = torch.matmul(randn1, randn2.T)
randn3, randn3.shape

(tensor([[ 0.5595,  0.4036],
         [-0.5087,  0.2792]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [51]:
# Find max
max = torch.max(rand3)

# Find min
min = torch.min(randn3)
max, min

(tensor(4.7471), tensor(-0.5087))

### 9. Find the maximum and minimum index values of the output of 7.

In [58]:
# Find arg max
max_args = torch.argmax(randn3)
# Find arg min
min_args = torch.argmin(randn3)
max_args, min_args

(tensor(0), tensor(2))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
