In [64]:
import torch
torch.__version__

'2.7.1+cpu'

In [65]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [66]:
TENSOR.ndim

3

In [6]:
TENSOR.shape

torch.Size([1, 3, 3])

In [7]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
TENSORTEST = torch.tensor([[[1,2,3,6,8],
                            [5,3,6,8,8],
                            [3434, 355, 55,8,8]]])
TENSORTEST


tensor([[[   1,    2,    3,    6,    8],
         [   5,    3,    6,    8,    8],
         [3434,  355,   55,    8,    8]]])

In [9]:
### RAndom tensors

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7407, 0.8011, 0.8069, 0.4947],
        [0.4056, 0.4753, 0.4159, 0.0513],
        [0.3351, 0.5623, 0.2748, 0.1022]])

In [10]:
random_tensor.ndim

2

In [11]:
# tensor similiar shape to an image

random_image_size_tensor = torch.rand(size=(224,224,3)) # height width colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [12]:
torch.rand(3,3)

tensor([[0.8424, 0.0224, 0.3570],
        [0.5115, 0.2877, 0.9736],
        [0.2259, 0.0112, 0.3270]])

In [13]:
# Create a tensor of all zeros 

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
ones.dtype

torch.float32

In [17]:
random_tensor.dtype

torch.float32

In [18]:
# RAnge

one_to_ten = torch.arange(1, 10)

one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None, # datatype
                               device= None, # "CPU" or "CUDA"
                               requires_grad=False) # track gradient
float_32_tensor

tensor([3., 6., 9.])

In [21]:
float_32_tensor.dtype

torch.float32

In [22]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
float_multi = float_16_tensor * float_32_tensor 
float_multi, float_multi.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [24]:
int_32_tensor = torch.tensor( [3, 6 ,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [25]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [44]:
x = torch.arange(0,100,10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
print(f"min: {x.min()}")
print(f"max: {x.max()}")
print(f"posMin: {x.argmin()}")
print(f"posMax: {x.argmax()}")
x.sum()

min: 0
max: 90
posMin: 0
posMax: 9


tensor(450)

In [62]:
x1 = torch.arange(1., 8,)
x1, x1.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [67]:
x1_reshape = x1.reshape(1, 7)
x1_reshape, x1_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [69]:
# Tensor mit 12 Elementen erstellen
x = torch.randn(3, 4)  # Shape: (3, 4)
print(x.shape)  # torch.Size([3, 4])

# Mit .view() die Form ändern
y = x.view(2, 6)  # Shape: (2, 6) - gleiche 12 Elemente, anders angeordnet
print(y.shape)  # torch.Size([2, 6])

y, x

torch.Size([3, 4])
torch.Size([2, 6])


(tensor([[ 0.3888,  1.0265,  1.7638,  1.1687,  0.1769, -0.0667],
         [-0.8315,  0.8185, -0.2826,  0.1865, -1.6899, -0.0392]]),
 tensor([[ 0.3888,  1.0265,  1.7638,  1.1687],
         [ 0.1769, -0.0667, -0.8315,  0.8185],
         [-0.2826,  0.1865, -1.6899, -0.0392]]))