Setup (Agnostic Code)


In [ ]:
import torch
import numpy
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
torch.cpu.device_count()

1

Putting tensors (and models) on the GPU

In [ ]:
# default ist auf der CPU

tensor = torch.tensor([1, 2, 3], device="cpu")

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Tensor auf die GPU schieben

tensor_on_gpu = tensor.to(device) # Schiebt es auf das oben erkannte Gerät
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# Tensor auf CPU verschieben

    # Wenn der tensor auf GPU kann er nicht in NumPy transformiert werden

tensor_on_gpu.numpy()

tensor_back_on_cpu = tensor_on_gpu.cpu()

tensor_back_on_cpu

tensor([1, 2, 3])