In [1]:
import torch


In [27]:
x = torch.arange(1, 11, 0.5)
x

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000])

In [6]:
x.shape, x.dtype

(torch.Size([20]), torch.float32)

In [28]:
y = x.reshape(1, 20)
y

tensor([[ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
          5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
          9.0000,  9.5000, 10.0000, 10.5000]])

In [29]:
xy = y * x 
xy

tensor([[  1.0000,   2.2500,   4.0000,   6.2500,   9.0000,  12.2500,  16.0000,
          20.2500,  25.0000,  30.2500,  36.0000,  42.2500,  49.0000,  56.2500,
          64.0000,  72.2500,  81.0000,  90.2500, 100.0000, 110.2500]])

In [31]:
xy.reshape(1,4,5)

tensor([[[  1.0000,   2.2500,   4.0000,   6.2500,   9.0000],
         [ 12.2500,  16.0000,  20.2500,  25.0000,  30.2500],
         [ 36.0000,  42.2500,  49.0000,  56.2500,  64.0000],
         [ 72.2500,  81.0000,  90.2500, 100.0000, 110.2500]]])

In [35]:
xy[0][0]

tensor(1.)